from jinja2 import FileSystemLoader, Template, Environment
import os
import logging
import sys
import codecs
import random
import string
from datetime import datetime

from typing import List

class RendererContext:

    logger_ = logging.getLogger("root")
    templateBaseDir_ : str = None
    templateReferencePath_ : str = None

    # default constructor
    def __init__(self, customControler, templateReferencePath = os.getcwd()):
        self.templateReferencePath_ = templateReferencePath
        self.jinjaTemplateLoader_ = FileSystemLoader(templateReferencePath)
        self.jinjaTemplateEnv_ = Environment(loader=self.jinjaTemplateLoader_)
        self.controler = customControler

    def getHeader(self, commentCaracter: str = '#'):
        return f'{commentCaracter} do not modify (autogenerated by CI) at {self.getDateTime()}'

    def linfo(self, text: str):
        self.logger_.info(text)
        return '' # avoid printing None in templates
    def getEnv(self, varName: str):
        return os.environ[varName]
    def getDateTime(self):
        return datetime.now().strftime("%H:%M:%S")

    def generatePassword(self):
        self.logger_.info("generating password...")
        result_str = ''.join(random.choice( ''.join( [string.ascii_letters, '.*-_()[]'])) for i in range(10))
        return result_str

    def iif(self, condition, value1: str, value2: str) -> str:
        if condition and value1: 
            return value1
        return value2

    def default(self, value1: str, value2: str) -> str:
        if value1: 
            return value1
        return value2

    def renderTemplate(
        self, 
        templatePath: str, 
        data: object, 
        output: codecs.StreamReaderWriter = sys.stdout,
        dryRunSwitch: bool = False) -> str:
            
            # TODO implement infinite loops detection
            
            self.templateBaseDir_ =  os.path.dirname(templatePath)
            self.logger_.info(f'rendering {templatePath} to {output} ...')

            if os.path.exists(output) and os.path.isfile(output):
                self.logger_.info(f'{output} exists and is a file, overwriting ...')

            try :
                template = self.jinjaTemplateEnv_.get_template(templatePath)
                if ( not dryRunSwitch ):
                    template.stream(data, context= self, os=os).dump(output)
            except Exception as e:
                typeName: str = type(e).__name__
                errorMessage: str = None
                if typeName == 'TemplateSyntaxError':
                    errorMessage = f'ko : Exception {typeName} in {e.name} => {e.message} at line {e.lineno}'
                else:
                    errorMessage = f'ko : Exception {typeName} => {e}'
                self.logger_.error(errorMessage)
                raise e
            else :
                self.logger_.info(f'{templatePath} rendered')
            finally :
                if type(output) == 'codecs.StreamReaderWriter' :
                    output.close()
