from jinja2 import FileSystemLoader, Template, Environment
import os
import logging
import sys
import codecs
import random
import string
from urllib.parse import urljoin
from Models.CustomizeOneParameters import CustomizeOneParameters
from kubernetes import client,config,utils

from datetime import datetime

from typing import List
class RendererContextRenderingInstance():
    def __init__(
            self, 
            currentInput, parentContext, currentOutput, 
            currentTemplate):

        self.currentInput: str = currentInput
        self.parentContext: 'RendererContext' = parentContext
        self.currentOutput = currentOutput
        self.currentTemplate = currentTemplate

class RendererContext:

    logger_ = logging.getLogger("root")
    templateBaseDir_ : str = None
    templateReferencePath_ : str = None
    parentTemplateReferencePath_ : str = None
    currentRenderingContext: currentRenderingContext = None
    kube_api_: client.CoreV1Api = None

    # default constructor
    def __init__(self, customControler, templateReferencePath = os.getcwd(), parentTemplateReferencePath= None):
        self.templateReferencePath_ = templateReferencePath
        self.jinjaTemplateLoader_ = FileSystemLoader(templateReferencePath)
        self.jinjaTemplateEnv_ = Environment(loader=self.jinjaTemplateLoader_)
        self.controler = customControler
        self.logger_.info("initializing kube client ...")
        config.load_kube_config()
        self.kube_api_ = client.CoreV1Api(client.ApiClient())
        self.parentTemplateReferencePath_ = parentTemplateReferencePath


    def getHeader(self, commentCaracter: str = '#'):
        return f'{commentCaracter} do not modify (autogenerated by CI)'

    def getHeaderWithTimestamp(self, commentCaracter: str = '#'):
        return f'{commentCaracter} do not modify (autogenerated by CI) at {self.getDateTime()}'

    def kubeSecretExists(self, name: str, namespace: str) -> bool:
        self.logger_.info(f"looking for secret {name} in namespace {namespace} ...")
        try:
            _=self.kube_api_.read_namespaced_secret(
                namespace=namespace, name=name
            )
            return True
        except client.exceptions.ApiException as exception:
            if exception.status == 404:
                return False

    def linfo(self, text: str):
        self.logger_.info(text)
        return '' # avoid printing None in templates
    def getEnv(self, varName: str):
        return os.environ[varName]
    def getDateTime(self):
        return datetime.now().strftime("%H:%M:%S")

    def generatePassword(self):
        self.logger_.info("generating password...")
        result_str = ''.join(random.choice( ''.join( [string.ascii_letters, '.*-_()[]'])) for i in range(10))
        return result_str

    def urlJoin(self, base, url):
        return urljoin(base=base, url=url, allow_fragments=True)

    def iif(self, condition, value1: str, value2: str) -> str:
        if condition and value1: 
            return value1
        return value2

    def default(self, value1: str, value2: str) -> str:
        if value1: 
            return value1
        return value2

    def getCurrentData():
        return currentData


    def inlineRender(self, templatePath: str):

        # import Modules.EntryPoint as ep
        # subContextPath = os.path.realpath(os.path.join(self.templateReferencePath_,templatePath))

        # ep.validateArgsAndRun(CustomizeOneParameters(
        #     self.templateReferencePath_, input= self.currentData, input_format= self.)

        subContext = RendererContext(
            customControler= self.controler, 
            templateReferencePath= self.templateReferencePath_ )

        subContext.renderTemplate(
            templatePath= templatePath,
            data = self.currentRenderingContext.currentInput,
            output= self.currentRenderingContext.currentOutput)

        return ''

    def renderAsValidationDependency(self, templatePath: str):

        currentReferencePath = self.iif( 
                self.parentTemplateReferencePath_ is not None,
                self.parentTemplateReferencePath_,
                self.templateReferencePath_)

        subContext = RendererContext(
            customControler= self.controler, 
            templateReferencePath= currentReferencePath,
            parentTemplateReferencePath=os.path.join(
                self.templateReferencePath_, 
                os.path.dirname(templatePath))
        )

        templatePathSize = len(templatePath)
        currentOutput: str = os.path.join(currentReferencePath,
            templatePath[0:templatePathSize - 3])

        subContext.renderTemplate(
            templatePath= templatePath,
            data = self.currentRenderingContext.currentInput,
            output= currentOutput)

        return ''
        
    def renderTemplate(
        self, 
        templatePath: str, 
        data: object, 
        output: codecs.StreamReaderWriter = sys.stdout,
        dryRunSwitch: bool = False) -> str:
            
            self.currentRenderingContext = RendererContextRenderingInstance(
                currentInput=data, currentTemplate=templatePath,
                parentContext=self, currentOutput=output)

            # TODO implement infinite loops detection

            self.currentData = data
            
            self.templateBaseDir_ =  os.path.dirname(templatePath)

            self.logger_.info(f'template reference path is: {self.templateReferencePath_}')
            self.logger_.info(f'rendering {templatePath} to {output} ...')
            
            if isinstance(output, str) and \
                os.path.exists(output) and \
                os.path.isfile(output):
                    self.logger_.info(f'{output} exists and is a file, overwriting ...')

            try :
                template = self.jinjaTemplateEnv_.get_template(templatePath)
                if ( not dryRunSwitch ):
                    template.stream(data, context= self, os=os).dump(output)
            except Exception as e:
                typeName: str = type(e).__name__
                errorMessage: str = None
                if typeName == 'TemplateSyntaxError':
                    errorMessage = f'ko : Exception {typeName} in {e.name} => {e.message} at line {e.lineno}'
                else:
                    errorMessage = f'ko : Exception {typeName} => {e}'
                self.logger_.error(errorMessage)
                raise e
            else :
                self.logger_.info(f'{templatePath} rendered')
            finally :
                if type(output) == 'codecs.StreamReaderWriter' :
                    output.close()

