from jinja2 import FileSystemLoader, Template, Environment
import os
import logging
import sys
import codecs
from datetime import datetime

from typing import List

class RendererContext:

    logger_ = logging.getLogger("root")
    templateBaseDir_ : str = None
    templateReferencePath_ : str = None

    # default constructor
    def __init__(self, customControler, templateReferencePath = os.getcwd()):
        self.templateReferencePath_ = templateReferencePath
        self.jinjaTemplateLoader_ = FileSystemLoader(templateReferencePath)
        self.jinjaTemplateEnv_ = Environment(loader=self.jinjaTemplateLoader_)
        self.controler = customControler

    def getHeader(self, commentCaracter: str = '#'):
        return f'{commentCaracter} do not modify (autogenerated by CI) at {self.getDateTime()}'

    def linfo(self, text: str):
        self.logger_.info(text)
        return '' # avoid printing None in templates

    def getDateTime(self):
        return datetime.now().strftime("%H:%M:%S")

    def renderTemplate(
        self, 
        templatePath: str, 
        data: object, 
        output: codecs.StreamReaderWriter = sys.stdout,
        dryRunSwitch: bool = False) -> str:
            
            # TODO implement infinite loops detection
            
            self.templateBaseDir_ =  os.path.dirname(templatePath)
            self.logger_.info(f'rendering {templatePath} to {output} ...')

            if os.path.exists(output) and os.path.isfile(output):
                self.logger_.info(f'{output} exists and is a file, overwriting ...')

            try :
                template = self.jinjaTemplateEnv_.get_template(templatePath)
                if ( not dryRunSwitch ):
                    template.stream(data, context= self, os=os).dump(output)
            except Exception as e:
                typeName: str = type(e).__name__
                if typeName == 'TemplateSyntaxError':
                    self.logger_.error(f'ko : Exception {typeName} in {e.name} => {e.message} at line {e.lineno}')
                else:
                    self.logger_.error(f'ko : Exception {typeName} => {e}')
            else :
                self.logger_.info(f'{templatePath} rendered')
            finally :
                if type(output) == 'codecs.StreamReaderWriter' :
                    output.close()
