# require to run with docker compose --project-directory .
# ex : docker compose --project-directory . -f ./indus/docker/dev.docker-compose.yml up
version: '3.6'

# this file setup the dev-container
services:
  dev_container:
    build:
      context: .
      dockerfile: ./Dockerfile
      # target: dev_env
      #args:
        # JTE_DOCKER_REGISTRY_URL: my-docker-registry.fr
        # Empty variables just copy current shell variables inside container
        # JTE_BUILD_TIME_ENV:
    container_name: dev_container_core
    user: "dev:dev"
    # for debug
    #user: "root:root"
    # extra_hosts:
      # host.docker.internal: host-gateway
      # require a tunnel on host
      # overrided_host.fr: "127.0.0.1"

    # definition explicite
    env_file: .env
    environment:
        # to have poetry and pypi credentials inside dev container do not forget to set
        # JTE_RUN_TIME_ENV="
        # POETRY_HTTP_BASIC_JTE_PYPI_USERNAME=xxx
        # POETRY_HTTP_BASIC_JTE_PYPI_PASSWORD=xxx
        # "
        # before running docker-compose up
        JTE_RUN_TIME_ENV:
    network_mode: host
    restart: 
    entrypoint: /bin/bash
    command: [ "-c", "/bin/sleep 999999" ]
    # entrypoint: /docker-run-entrypoint.sh
    volumes:
      - type: bind
        source: ./
        target: /app/
        # env de dev vscode
      - type: volume
        source: jte_vscode
        target: /home/jte/.vscode-server
volumes:
  jte_vscode:

networks:
  jte:
    driver: bridge