import codecs
import logging
import os
import random
import string
import sys
from datetime import datetime
from typing import IO, Union
from urllib.parse import urljoin

from jinja2 import Environment, FileSystemLoader

class RendererContextRenderingInstance():
    def __init__(
            self,
            current_input, parent_context, current_output, 
            current_template):
        self.current_input: str = current_input
        self.parent_context: 'RendererContext' = parent_context
        self.current_output = current_output
        self.current_template = current_template

class RendererContext:

    _logger = logging.getLogger("root")
    _template_base_dir : str
    _template_reference_path : str
    _parent_template_reference_path : str
    current_rendering_context: 'RendererContextRenderingInstance'
    # kube_api_: client.CoreV1Api = None

    # default constructor
    def __init__(self, custom_controller, parent_template_reference_path = None, 
                 template_reference_path = os.getcwd()):
        self._template_reference_path = template_reference_path
        self._jinja_template_loader = FileSystemLoader(template_reference_path)
        self._jinja_template_env = Environment(loader=self._jinja_template_loader)
        self.controler = custom_controller

        # self._logger.info("initializing kube client ...")
        #config.load_kube_config()
        # self.kube_api_ = client.CoreV1Api(client.ApiClient())
        self._parent_template_reference_path = parent_template_reference_path
        self.current_data = None

    def get_header(self, commentCaracter: str = '#'):
        return f'{commentCaracter} do not modify (autogenerated by CI)'

    def get_header_with_timestamp(self, comment_caracter: str = '#'):
        return f'{comment_caracter} do not modify (autogenerated by CI) at {self.get_date_time()}'

    # def kubeSecretExists(self, name: str, namespace: str) -> bool:
    #     self.logger_.info(f"looking for secret {name} in namespace {namespace} ...")
    #     try:
    #         _=self.kube_api_.read_namespaced_secret(
    #             namespace=namespace, name=name
    #         )
    #         return True
    #     except client.exceptions.ApiException as exception:
    #         if exception.status == 404:
    #             return False

    def linfo(self, text: str):
        self._logger.info(text)
        return '' # avoid printing None in templates
    def get_env(self, varName: str):
        return os.environ[varName]
    def get_date_time(self):
        return datetime.now().strftime("%H:%M:%S")

    def generate_password(self):
        self._logger.info("generating password...")
        result_str = ''.join(random.choice( ''.join( [string.ascii_letters, '.*-_()[]'])) for i in range(10))
        return result_str

    def url_join(self, base, url):
        return urljoin(base=base, url=url, allow_fragments=True)

    def iif(self, condition, value1: str, value2: str) -> str:
        if condition and value1:
            return value1
        return value2

    def required_template_variables(self, variables_names: list[str]):
        
        for variable_name in variables_names:
            if variable_name not in self.current_rendering_context.current_input:
                raise ValueError(f'variable {variable_name} is required by template {self.current_rendering_context.current_template} but is not present in current input')
            
        return '# generated with vars: ' + ', '.join(variables_names)
        

    def get_current_data(self):
        return self.current_data


    def inline_render(self, template_path: str):

        # import Modules.EntryPoint as ep
        # subContextPath = os.path.realpath(os.path.join(self.templateReferencePath_,templatePath))

        # ep.validateArgsAndRun(CustomizeOneParameters(
        #     self.templateReferencePath_, input= self.currentData, input_format= self.)

        sub_context = RendererContext(
            custom_controller= self.controler, 
            template_reference_path= self._template_reference_path )

        sub_context.render_template(
            template_path= template_path,
            data = self.current_rendering_context.current_input,
            output= self.current_rendering_context.current_output)

        return ''

    def render_as_validation_dependency(self, template_path: str):

        current_reference_path = self.iif( 
                self._parent_template_reference_path is not None,
                self._parent_template_reference_path,
                self._template_reference_path)

        sub_context = RendererContext(
            custom_controller= self.controler,
            template_reference_path= current_reference_path,
            parent_template_reference_path=os.path.join(
                self._template_reference_path,
                os.path.dirname(template_path))
        )

        template_path_size = len(template_path)
        current_output: str = os.path.join(current_reference_path,
            template_path[0:template_path_size - 3])

        sub_context.render_template(
            template_path= template_path,
            data = self.current_rendering_context.current_input,
            output= current_output)

        return ''
    
    def include_file(self, path: str):
        
        current_reference_path = self.iif( 
                self._parent_template_reference_path is not None,
                self._parent_template_reference_path,
                self._template_reference_path)

        file_content: str
        with open(os.path.join(current_reference_path, path), 'r', encoding='utf-8') as file:
            file_content = file.read()
            
        return file_content
        
    
    def render_template(
        self,
        template_path: str,
        data: object,
        output: Union[codecs.StreamReaderWriter, str],
        dry_run_switch: bool = False) -> str:
            
            self.current_rendering_context = RendererContextRenderingInstance(
                current_input=data, current_template=template_path,
                parent_context=self, current_output=output)

            # TODO implement infinite loops detection

            self.current_data = data
            
            self._template_base_dir =  os.path.dirname(template_path)
    
            self._logger.info('template reference path is: %s', self._template_reference_path)
            self._logger.info('rendering %s to %s ...', template_path, output)
            
            if isinstance(output, str) and \
                os.path.exists(output) and \
                os.path.isfile(output):
                    self._logger.info('%s exists and is a file, overwriting ...', output)

            try :
                template = self._jinja_template_env.get_template(template_path)
                if ( not dry_run_switch ):
                    template.stream(data, context= self, os=os).dump(output)
            except Exception as e:
                type_name: str = type(e).__name__
                error_message: str
                if type_name == 'TemplateSyntaxError':
                    error_message = f'ko : Exception {type_name} in {e.name} => {e.message} at line {e.lineno}'
                else:
                    error_message = f'ko : Exception {type_name} => {e}'
                self._logger.error(error_message)
                raise e
            else :
                self._logger.info('%s rendered', template_path)
            finally :
                if type(output) == 'codecs.StreamReaderWriter' :
                    output.close()

